package client.viewmanager;

public enum ViewNames {

    BACKGROUND_SCREEN,
    CONNECT,
    RECONNECT,
    START,
    SIGN_UP,
    SIGN_IN,
    ACCOUNT_SETTINGS,
    CHANGE_USERNAME,
    CHANGE_PASSWORD,
    USER_MENU,

    CUSTOMER_SHARED_LISTS,
    CUSTOMER_SHOP_CHOOSE,
    CUSTOMER_LIST_CHOOSE,
    CUSTOMER_LIST_CREATE,
    CUSTOMER_LIST_EDIT,
    CUSTOMER_LIST_SHARE,
    CUSTOMER_LIST_CLONE,
    CUSTOMER_LIST_ADD_PRODUCT,

    SHOP_MANAGER_SHOP_CHOOSE,
    SHOP_MANAGER_SHOP_CREATE,
    SHOP_MANAGER_SHOP_EDIT,
    SHOP_MANAGER_SHOP_ADD_PRODUCT,

    CONFIRM

}
